/// <reference lib="dom" />
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by generate-attribute-types.js using HTML element
// data from the html-validate module.

interface Stringable {
  toString(): string;
}

export type RefCallback<T extends Element> = (element: T) => void;

export interface EventAttributes {
  onAbort?: GlobalEventHandlers["onabort"];
  onAbortCapture?: GlobalEventHandlers["onabort"];
  onAnimationCancel?: GlobalEventHandlers["onanimationcancel"];
  onAnimationCancelCapture?: GlobalEventHandlers["onanimationcancel"];
  onAnimationEnd?: GlobalEventHandlers["onanimationend"];
  onAnimationEndCapture?: GlobalEventHandlers["onanimationend"];
  onAnimationIteration?: GlobalEventHandlers["onanimationiteration"];
  onAnimationIterationCapture?: GlobalEventHandlers["onanimationiteration"];
  onAnimationStart?: GlobalEventHandlers["onanimationstart"];
  onAnimationStartCapture?: GlobalEventHandlers["onanimationstart"];
  onAuxClick?: GlobalEventHandlers["onauxclick"];
  onAuxClickCapture?: GlobalEventHandlers["onauxclick"];
  onBlur?: GlobalEventHandlers["onblur"];
  onBlurCapture?: GlobalEventHandlers["onblur"];
  onCanplay?: GlobalEventHandlers["oncanplay"];
  onCanplayCapture?: GlobalEventHandlers["oncanplay"];
  onCanplayThrough?: GlobalEventHandlers["oncanplaythrough"];
  onCanplayThroughCapture?: GlobalEventHandlers["oncanplaythrough"];
  onChange?: GlobalEventHandlers["onchange"];
  onChangeCapture?: GlobalEventHandlers["onchange"];
  onClick?: GlobalEventHandlers["onclick"];
  onClickCapture?: GlobalEventHandlers["onclick"];
  onClose?: GlobalEventHandlers["onclose"];
  onCloseCapture?: GlobalEventHandlers["onclose"];
  onContextMenu?: GlobalEventHandlers["oncontextmenu"];
  onContextMenuCapture?: GlobalEventHandlers["oncontextmenu"];
  onCueChange?: GlobalEventHandlers["oncuechange"];
  onCueChangeCapture?: GlobalEventHandlers["oncuechange"];
  onDblClick?: GlobalEventHandlers["ondblclick"];
  onDblClickCapture?: GlobalEventHandlers["ondblclick"];
  onDrag?: GlobalEventHandlers["ondrag"];
  onDragCapture?: GlobalEventHandlers["ondrag"];
  onDragEnd?: GlobalEventHandlers["ondragend"];
  onDragEndCapture?: GlobalEventHandlers["ondragend"];
  onDragEnter?: GlobalEventHandlers["ondragenter"];
  onDragEnterCapture?: GlobalEventHandlers["ondragenter"];
  onDragLeave?: GlobalEventHandlers["ondragleave"];
  onDragLeaveCapture?: GlobalEventHandlers["ondragleave"];
  onDragOver?: GlobalEventHandlers["ondragover"];
  onDragOverCapture?: GlobalEventHandlers["ondragover"];
  onDragStart?: GlobalEventHandlers["ondragstart"];
  onDragStartCapture?: GlobalEventHandlers["ondragstart"];
  onDrop?: GlobalEventHandlers["ondrop"];
  onDropCapture?: GlobalEventHandlers["ondrop"];
  onDurationChange?: GlobalEventHandlers["ondurationchange"];
  onDurationChangeCapture?: GlobalEventHandlers["ondurationchange"];
  onEmptied?: GlobalEventHandlers["onemptied"];
  onEmptiedCapture?: GlobalEventHandlers["onemptied"];
  onEnded?: GlobalEventHandlers["onended"];
  onEndedCapture?: GlobalEventHandlers["onended"];
  onError?: GlobalEventHandlers["onerror"];
  onErrorCapture?: GlobalEventHandlers["onerror"];
  onFocus?: GlobalEventHandlers["onfocus"];
  onFocusCapture?: GlobalEventHandlers["onfocus"];
  onFormData?: GlobalEventHandlers["onformdata"];
  onFormDataCapture?: GlobalEventHandlers["onformdata"];
  onGotPointerCapture?: GlobalEventHandlers["ongotpointercapture"];
  onInput?: GlobalEventHandlers["oninput"];
  onInputCapture?: GlobalEventHandlers["oninput"];
  onInvalid?: GlobalEventHandlers["oninvalid"];
  onInvalidCapture?: GlobalEventHandlers["oninvalid"];
  onKeyDown?: GlobalEventHandlers["onkeydown"];
  onKeyDownCapture?: GlobalEventHandlers["onkeydown"];
  onKeyPress?: GlobalEventHandlers["onkeypress"];
  onKeyPressCapture?: GlobalEventHandlers["onkeypress"];
  onKeyUp?: GlobalEventHandlers["onkeyup"];
  onKeyUpCapture?: GlobalEventHandlers["onkeyup"];
  onLoad?: GlobalEventHandlers["onload"];
  onLoadCapture?: GlobalEventHandlers["onload"];
  onLoadedData?: GlobalEventHandlers["onloadeddata"];
  onLoadedDataCapture?: GlobalEventHandlers["onloadeddata"];
  onLoadedMetadata?: GlobalEventHandlers["onloadedmetadata"];
  onLoadedMetadataCapture?: GlobalEventHandlers["onloadedmetadata"];
  onLoadStart?: GlobalEventHandlers["onloadstart"];
  onLoadStartCapture?: GlobalEventHandlers["onloadstart"];
  onLostPointerCapture?: GlobalEventHandlers["onlostpointercapture"];
  onMouseDown?: GlobalEventHandlers["onmousedown"];
  onMouseDownCapture?: GlobalEventHandlers["onmousedown"];
  onMouseEnter?: GlobalEventHandlers["onmouseenter"];
  onMouseEnterCapture?: GlobalEventHandlers["onmouseenter"];
  onMouseLeave?: GlobalEventHandlers["onmouseleave"];
  onMouseLeaveCapture?: GlobalEventHandlers["onmouseleave"];
  onMouseMove?: GlobalEventHandlers["onmousemove"];
  onMouseMoveCapture?: GlobalEventHandlers["onmousemove"];
  onMouseOut?: GlobalEventHandlers["onmouseout"];
  onMouseOutCapture?: GlobalEventHandlers["onmouseout"];
  onMouseOver?: GlobalEventHandlers["onmouseover"];
  onMouseOverCapture?: GlobalEventHandlers["onmouseover"];
  onMouseUp?: GlobalEventHandlers["onmouseup"];
  onMouseUpCapture?: GlobalEventHandlers["onmouseup"];
  onPause?: GlobalEventHandlers["onpause"];
  onPauseCapture?: GlobalEventHandlers["onpause"];
  onPlay?: GlobalEventHandlers["onplay"];
  onPlayCapture?: GlobalEventHandlers["onplay"];
  onPlaying?: GlobalEventHandlers["onplaying"];
  onPlayingCapture?: GlobalEventHandlers["onplaying"];
  onPointerCancel?: GlobalEventHandlers["onpointercancel"];
  onPointerCancelCapture?: GlobalEventHandlers["onpointercancel"];
  onPointerDown?: GlobalEventHandlers["onpointerdown"];
  onPointerDownCapture?: GlobalEventHandlers["onpointerdown"];
  onPointerEnter?: GlobalEventHandlers["onpointerenter"];
  onPointerEnterCapture?: GlobalEventHandlers["onpointerenter"];
  onPointerLeave?: GlobalEventHandlers["onpointerleave"];
  onPointerLeaveCapture?: GlobalEventHandlers["onpointerleave"];
  onPointerMove?: GlobalEventHandlers["onpointermove"];
  onPointerMoveCapture?: GlobalEventHandlers["onpointermove"];
  onPointerOut?: GlobalEventHandlers["onpointerout"];
  onPointerOutCapture?: GlobalEventHandlers["onpointerout"];
  onPointerOver?: GlobalEventHandlers["onpointerover"];
  onPointerOverCapture?: GlobalEventHandlers["onpointerover"];
  onPointerUp?: GlobalEventHandlers["onpointerup"];
  onPointerUpCapture?: GlobalEventHandlers["onpointerup"];
  onProgress?: GlobalEventHandlers["onprogress"];
  onProgressCapture?: GlobalEventHandlers["onprogress"];
  onRateChange?: GlobalEventHandlers["onratechange"];
  onRateChangeCapture?: GlobalEventHandlers["onratechange"];
  onReset?: GlobalEventHandlers["onreset"];
  onResetCapture?: GlobalEventHandlers["onreset"];
  onResize?: GlobalEventHandlers["onresize"];
  onResizeCapture?: GlobalEventHandlers["onresize"];
  onScroll?: GlobalEventHandlers["onscroll"];
  onScrollCapture?: GlobalEventHandlers["onscroll"];
  onSecurityPolicyViolation?: GlobalEventHandlers["onsecuritypolicyviolation"];
  onSecurityPolicyViolationCapture?: GlobalEventHandlers["onsecuritypolicyviolation"];
  onSeeked?: GlobalEventHandlers["onseeked"];
  onSeekedCapture?: GlobalEventHandlers["onseeked"];
  onSeeking?: GlobalEventHandlers["onseeking"];
  onSeekingCapture?: GlobalEventHandlers["onseeking"];
  onSelect?: GlobalEventHandlers["onselect"];
  onSelectCapture?: GlobalEventHandlers["onselect"];
  onSelectionChange?: GlobalEventHandlers["onselectionchange"];
  onSelectionChangeCapture?: GlobalEventHandlers["onselectionchange"];
  onSelectStart?: GlobalEventHandlers["onselectstart"];
  onSelectStartCapture?: GlobalEventHandlers["onselectstart"];
  onSlotChange?: GlobalEventHandlers["onslotchange"];
  onSlotChangeCapture?: GlobalEventHandlers["onslotchange"];
  onStalled?: GlobalEventHandlers["onstalled"];
  onStalledCapture?: GlobalEventHandlers["onstalled"];
  onSubmit?: GlobalEventHandlers["onsubmit"];
  onSubmitCapture?: GlobalEventHandlers["onsubmit"];
  onSuspend?: GlobalEventHandlers["onsuspend"];
  onSuspendCapture?: GlobalEventHandlers["onsuspend"];
  onTimeUpdate?: GlobalEventHandlers["ontimeupdate"];
  onTimeUpdateCapture?: GlobalEventHandlers["ontimeupdate"];
  onToggle?: GlobalEventHandlers["ontoggle"];
  onToggleCapture?: GlobalEventHandlers["ontoggle"];
  onTouchCancel?: GlobalEventHandlers["ontouchcancel"];
  onTouchCancelCapture?: GlobalEventHandlers["ontouchcancel"];
  onTouchEnd?: GlobalEventHandlers["ontouchend"];
  onTouchEndCapture?: GlobalEventHandlers["ontouchend"];
  onTouchMove?: GlobalEventHandlers["ontouchmove"];
  onTouchMoveCapture?: GlobalEventHandlers["ontouchmove"];
  onTouchStart?: GlobalEventHandlers["ontouchstart"];
  onTouchStartCapture?: GlobalEventHandlers["ontouchstart"];
  onTransitionCancel?: GlobalEventHandlers["ontransitioncancel"];
  onTransitionCancelCapture?: GlobalEventHandlers["ontransitioncancel"];
  onTransitionEnd?: GlobalEventHandlers["ontransitionend"];
  onTransitionEndCapture?: GlobalEventHandlers["ontransitionend"];
  onTransitionRun?: GlobalEventHandlers["ontransitionrun"];
  onTransitionRunCapture?: GlobalEventHandlers["ontransitionrun"];
  onTransitionStart?: GlobalEventHandlers["ontransitionstart"];
  onTransitionStartCapture?: GlobalEventHandlers["ontransitionstart"];
  onVolumeChange?: GlobalEventHandlers["onvolumechange"];
  onVolumeChangeCapture?: GlobalEventHandlers["onvolumechange"];
  onWaiting?: GlobalEventHandlers["onwaiting"];
  onWaitingCapture?: GlobalEventHandlers["onwaiting"];
  onWheel?: GlobalEventHandlers["onwheel"];
  onWheelCapture?: GlobalEventHandlers["onwheel"];
}

export interface AriaAttributes {
  "aria-activedescendant"?: string;
  "aria-atomic"?: string;
  "aria-autocomplete"?: string;
  "aria-busy"?: string;
  "aria-checked"?: string;
  "aria-colcount"?: string;
  "aria-colindex"?: string;
  "aria-colspan"?: string;
  "aria-controls"?: string;
  "aria-current"?: string;
  "aria-describedby"?: string;
  "aria-details"?: string;
  "aria-disabled"?: string;
  "aria-dropeffect"?: string;
  "aria-errormessage"?: string;
  "aria-expanded"?: string;
  "aria-flowto"?: string;
  "aria-grabbed"?: string;
  "aria-haspopup"?: string;
  "aria-hidden"?: string;
  "aria-invalid"?: string;
  "aria-keyshortcuts"?: string;
  "aria-label"?: string;
  "aria-labelledby"?: string;
  "aria-level"?: string;
  "aria-live"?: string;
  "aria-modal"?: string;
  "aria-multiline"?: string;
  "aria-multiselectable"?: string;
  "aria-orientation"?: string;
  "aria-owns"?: string;
  "aria-placeholder"?: string;
  "aria-posinset"?: string;
  "aria-pressed"?: string;
  "aria-readonly"?: string;
  "aria-relevant"?: string;
  "aria-required"?: string;
  "aria-roledescription"?: string;
  "aria-rowcount"?: string;
  "aria-rowindex"?: string;
  "aria-rowspan"?: string;
  "aria-selected"?: string;
  "aria-setsize"?: string;
  "aria-sort"?: string;
  "aria-valuemax"?: string;
  "aria-valuemin"?: string;
  "aria-valuenow"?: string;
  "aria-valuetext"?: string;
  role?: string;
}

export interface GlobalHtmlAttributes extends EventAttributes, AriaAttributes {
  style?: string | Stringable | Partial<CSSStyleDeclaration>;
  className?: string | Stringable;
  contenteditable?: "true" | "false";
  dir?: "ltr" | "rtl" | "auto";
  draggable?: "true" | "false";
  hidden?: boolean;
  id?: string;
  inert?: boolean;
  spellcheck?: "true" | "false";
  tabindex?: string;
  accesskey?: string;
  autocapitalize?: string;
  autofocus?: boolean;
  class?: string;
  enterkeyhint?: string;
  inputmode?: string;
  is?: string;
  itemid?: string;
  itemprop?: string;
  itemref?: string;
  itemscope?: string;
  itemtype?: string;
  lang?: string;
  nonce?: string;
  popover?: string;
  slot?: string;
  title?: string;
  translate?: string;
  writingsuggestions?: string;
}

export interface HtmlAAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["a"]>;
  children?: JSX.Nodes;
  download?: string;
  href?: string;
  hreflang?: string;
  itemprop?: string;
  ping?: string;
  referrerpolicy?:
    | ""
    | "no-referrer"
    | "no-referrer-when-downgrade"
    | "same-origin"
    | "origin"
    | "strict-origin"
    | "origin-when-cross-origin"
    | "strict-origin-when-cross-origin"
    | "unsafe-url";
  rel?: string;
  target?: string;
  type?: string;
  rev?: string;
}

export interface HtmlAbbrAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["abbr"]>;
  children?: JSX.Nodes;
}

export interface HtmlAddressAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["address"]>;
  children?: JSX.Nodes;
}

export interface HtmlAreaAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["area"]>;
  alt?: string;
  coords?: string;
  download?: string;
  itemprop?: string;
  ping?: string;
  referrerpolicy?:
    | ""
    | "no-referrer"
    | "no-referrer-when-downgrade"
    | "same-origin"
    | "origin"
    | "strict-origin"
    | "origin-when-cross-origin"
    | "strict-origin-when-cross-origin"
    | "unsafe-url";
  rel?: string;
  shape?: "rect" | "circle" | "poly" | "default";
  target?: string;
  href?: string;
  hreflang?: string;
  type?: string;
}

export interface HtmlArticleAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["article"]>;
  children?: JSX.Nodes;
}

export interface HtmlAsideAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["aside"]>;
  children?: JSX.Nodes;
}

export interface HtmlAudioAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["audio"]>;
  children?: JSX.Nodes;
  crossorigin?: "anonymous" | "use-credentials";
  itemprop?: string;
  preload?: "none" | "metadata" | "auto";
  autoplay?: string;
  controls?: string;
  loop?: string;
  muted?: string;
  src?: string;
}

export interface HtmlBAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["b"]>;
  children?: JSX.Nodes;
}

export interface HtmlBaseAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["base"]>;
  href?: string;
  target?: string;
}

export interface HtmlBdiAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["bdi"]>;
  children?: JSX.Nodes;
}

export interface HtmlBdoAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["bdo"]>;
  children?: JSX.Nodes;
}

export interface HtmlBlockquoteAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["blockquote"]>;
  children?: JSX.Nodes;
  cite?: string;
}

export interface HtmlBodyAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["body"]>;
  children?: JSX.Nodes;
}

export interface HtmlBrAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["br"]>;
}

export interface HtmlButtonAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["button"]>;
  children?: JSX.Nodes;
  autofocus?: boolean;
  disabled?: boolean;
  formaction?: string;
  formenctype?: string;
  formmethod?: "get" | "post" | "dialog";
  formnovalidate?: boolean;
  formtarget?: string;
  type?: "submit" | "reset" | "button";
  form?: string;
  name?: string;
  popovertarget?: string;
  popovertargetaction?: string;
  value?: string;
}

export interface HtmlCanvasAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["canvas"]>;
  children?: JSX.Nodes;
  height?: string;
  width?: string;
}

export interface HtmlCaptionAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["caption"]>;
  children?: JSX.Nodes;
}

export interface HtmlCiteAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["cite"]>;
  children?: JSX.Nodes;
}

export interface HtmlCodeAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["code"]>;
  children?: JSX.Nodes;
}

export interface HtmlColAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["col"]>;
  span?: number | string;
}

export interface HtmlColgroupAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["colgroup"]>;
  children?: JSX.Nodes;
  span?: number | string;
  align?: string;
  char?: string;
  charoff?: string;
  valign?: string;
  width?: string;
}

export interface HtmlDataAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["data"]>;
  children?: JSX.Nodes;
  value?: string;
}

export interface HtmlDatalistAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["datalist"]>;
  children?: JSX.Nodes;
}

export interface HtmlDdAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["dd"]>;
  children?: JSX.Nodes;
}

export interface HtmlDelAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["del"]>;
  children?: JSX.Nodes;
  cite?: string;
  datetime?: string;
}

export interface HtmlDetailsAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["details"]>;
  children?: JSX.Nodes;
  open?: boolean;
  name?: string;
}

export interface HtmlDfnAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["dfn"]>;
  children?: JSX.Nodes;
}

export interface HtmlDialogAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["dialog"]>;
  children?: JSX.Nodes;
  open?: boolean;
}

export interface HtmlDivAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["div"]>;
  children?: JSX.Nodes;
}

export interface HtmlDlAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["dl"]>;
  children?: JSX.Nodes;
}

export interface HtmlDtAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["dt"]>;
  children?: JSX.Nodes;
}

export interface HtmlEmAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["em"]>;
  children?: JSX.Nodes;
}

export interface HtmlEmbedAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["embed"]>;
  height?: number | string;
  src: string;
  title: string;
  width?: number | string;
  type?: string;
}

export interface HtmlFieldsetAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["fieldset"]>;
  children?: JSX.Nodes;
  disabled?: boolean;
  form?: string;
  name?: string;
}

export interface HtmlFigcaptionAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["figcaption"]>;
  children?: JSX.Nodes;
}

export interface HtmlFigureAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["figure"]>;
  children?: JSX.Nodes;
}

export interface HtmlFooterAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["footer"]>;
  children?: JSX.Nodes;
}

export interface HtmlFormAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["form"]>;
  children?: JSX.Nodes;
  action?: string;
  autocomplete?: "on" | "off";
  method?: "get" | "post" | "dialog";
  novalidate?: boolean;
  rel?: string;
  target?: string;
  "accept-charset"?: string;
  enctype?: string;
  name?: string;
}

export interface HtmlH1Attributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["h1"]>;
  children?: JSX.Nodes;
}

export interface HtmlH2Attributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["h2"]>;
  children?: JSX.Nodes;
}

export interface HtmlH3Attributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["h3"]>;
  children?: JSX.Nodes;
}

export interface HtmlH4Attributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["h4"]>;
  children?: JSX.Nodes;
}

export interface HtmlH5Attributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["h5"]>;
  children?: JSX.Nodes;
}

export interface HtmlH6Attributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["h6"]>;
  children?: JSX.Nodes;
}

export interface HtmlHeadAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["head"]>;
  children?: JSX.Nodes;
}

export interface HtmlHeaderAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["header"]>;
  children?: JSX.Nodes;
}

export interface HtmlHgroupAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["hgroup"]>;
  children?: JSX.Nodes;
}

export interface HtmlHrAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["hr"]>;
}

export interface HtmlHtmlAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["html"]>;
  children?: JSX.Nodes;
  lang: string;
  manifest?: string;
}

export interface HtmlIAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["i"]>;
  children?: JSX.Nodes;
}

export interface HtmlIframeAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["iframe"]>;
  children?: JSX.Nodes;
  height?: number | string;
  referrerpolicy?:
    | ""
    | "no-referrer"
    | "no-referrer-when-downgrade"
    | "same-origin"
    | "origin"
    | "strict-origin"
    | "origin-when-cross-origin"
    | "strict-origin-when-cross-origin"
    | "unsafe-url";
  src?: string;
  title: string;
  width?: number | string;
  allow?: string;
  allowfullscreen?: string;
  allowpaymentrequest?: string;
  allowusermedia?: string;
  loading?: string;
  longdesc?: string;
  name?: string;
  sandbox?: string;
  srcdoc?: string;
}

export interface HtmlImgAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["img"]>;
  crossorigin?: "anonymous" | "use-credentials";
  decoding?: "sync" | "async" | "auto";
  height?: number | string;
  ismap?: boolean;
  referrerpolicy?:
    | ""
    | "no-referrer"
    | "no-referrer-when-downgrade"
    | "same-origin"
    | "origin"
    | "strict-origin"
    | "origin-when-cross-origin"
    | "strict-origin-when-cross-origin"
    | "unsafe-url";
  src: string;
  srcset?: string;
  width?: number | string;
  alt?: string;
  fetchpriority?: string;
  loading?: string;
  longdesc?: string;
  sizes?: string;
  usemap?: string;
}

export interface HtmlInputAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["input"]>;
  autofocus?: boolean;
  capture?: "environment" | "user";
  checked?: boolean;
  disabled?: boolean;
  formaction?: string;
  formenctype?: string;
  formmethod?: "get" | "post" | "dialog";
  formnovalidate?: boolean;
  formtarget?: string;
  inputmode?:
    | "none"
    | "text"
    | "decimal"
    | "numeric"
    | "tel"
    | "search"
    | "email"
    | "url";
  multiple?: boolean;
  readonly?: boolean;
  required?: boolean;
  type?:
    | "button"
    | "checkbox"
    | "color"
    | "date"
    | "datetime-local"
    | "email"
    | "file"
    | "hidden"
    | "image"
    | "month"
    | "number"
    | "password"
    | "radio"
    | "range"
    | "reset"
    | "search"
    | "submit"
    | "tel"
    | "text"
    | "time"
    | "url"
    | "week";
  accept?: string;
  alt?: string;
  autocomplete?: string;
  dirname?: string;
  form?: string;
  height?: string;
  list?: string;
  max?: string;
  maxlength?: string;
  min?: string;
  minlength?: string;
  name?: string;
  pattern?: string;
  placeholder?: string;
  popovertarget?: string;
  popovertargetaction?: string;
  size?: string;
  src?: string;
  step?: string;
  value?: string;
  width?: string;
}

export interface HtmlInsAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["ins"]>;
  children?: JSX.Nodes;
  cite?: string;
  datetime?: string;
}

export interface HtmlKbdAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["kbd"]>;
  children?: JSX.Nodes;
}

export interface HtmlLabelAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["label"]>;
  children?: JSX.Nodes;
  for?: string;
  form?: string;
}

export interface HtmlLegendAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["legend"]>;
  children?: JSX.Nodes;
}

export interface HtmlLiAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["li"]>;
  children?: JSX.Nodes;
  value?: string;
}

export interface HtmlLinkAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["link"]>;
  as?:
    | "audio"
    | "audioworklet"
    | "document"
    | "embed"
    | "fetch"
    | "font"
    | "frame"
    | "iframe"
    | "image"
    | "manifest"
    | "object"
    | "paintworklet"
    | "report"
    | "script"
    | "serviceworker"
    | "sharedworker"
    | "style"
    | "track"
    | "video"
    | "webidentity"
    | "worker"
    | "xslt";
  blocking?: "render";
  crossorigin?: "anonymous" | "use-credentials";
  disabled?: boolean;
  href: string;
  integrity?: string;
  referrerpolicy?:
    | ""
    | "no-referrer"
    | "no-referrer-when-downgrade"
    | "same-origin"
    | "origin"
    | "strict-origin"
    | "origin-when-cross-origin"
    | "strict-origin-when-cross-origin"
    | "unsafe-url";
  rel?: string;
  color?: string;
  fetchpriority?: string;
  hreflang?: string;
  imagesizes?: string;
  imagesrcset?: string;
  media?: string;
  rev?: string;
  sizes?: string;
  type?: string;
}

export interface HtmlMainAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["main"]>;
  children?: JSX.Nodes;
}

export interface HtmlMapAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["map"]>;
  children?: JSX.Nodes;
  name: string;
}

export interface HtmlMarkAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["mark"]>;
  children?: JSX.Nodes;
}

export interface HtmlMathAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<MathMLElement>;
  children?: JSX.Nodes;
  dir?: "ltr" | "rtl";
  display?: "block" | "inline";
  overflow?: "linebreak" | "scroll" | "elide" | "truncate" | "scale";
}

export interface HtmlMenuAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["menu"]>;
  children?: JSX.Nodes;
  compact?: string;
}

export interface HtmlMetaAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["meta"]>;
  charset?: "utf-8";
  content?: string;
  itemprop?: string;
  name?: string;
  "http-equiv"?: string;
  media?: string;
}

export interface HtmlMeterAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["meter"]>;
  children?: JSX.Nodes;
  high?: string;
  low?: string;
  max?: string;
  min?: string;
  optimum?: string;
  value?: string;
}

export interface HtmlNavAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["nav"]>;
  children?: JSX.Nodes;
}

export interface HtmlNoscriptAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["noscript"]>;
  children?: JSX.Nodes;
}

export interface HtmlObjectAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["object"]>;
  children?: JSX.Nodes;
  blocking?: "render";
  data: string;
  height?: number | string;
  name?: string;
  width?: number | string;
  form?: string;
  type?: string;
  typemustmatch?: string;
  usemap?: string;
}

export interface HtmlOlAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["ol"]>;
  children?: JSX.Nodes;
  reversed?: boolean;
  type?: "a" | "A" | "i" | "I" | "1";
  start?: string;
}

export interface HtmlOptgroupAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["optgroup"]>;
  children?: JSX.Nodes;
  disabled?: boolean;
  label?: string;
}

export interface HtmlOptionAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["option"]>;
  children?: JSX.Nodes;
  disabled?: boolean;
  selected?: boolean;
  label?: string;
  value?: string;
}

export interface HtmlOutputAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["output"]>;
  children?: JSX.Nodes;
  for?: string;
  form?: string;
  name?: string;
}

export interface HtmlPAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["p"]>;
  children?: JSX.Nodes;
}

export interface HtmlParamAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["param"]>;
  name?: string;
  value?: string;
}

export interface HtmlPictureAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["picture"]>;
  children?: JSX.Nodes;
}

export interface HtmlPreAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["pre"]>;
  children?: JSX.Nodes;
}

export interface HtmlProgressAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["progress"]>;
  children?: JSX.Nodes;
  max?: string;
  value?: string;
}

export interface HtmlQAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["q"]>;
  children?: JSX.Nodes;
  cite?: string;
}

export interface HtmlRpAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["rp"]>;
  children?: JSX.Nodes;
}

export interface HtmlRtAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["rt"]>;
  children?: JSX.Nodes;
}

export interface HtmlRubyAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["ruby"]>;
  children?: JSX.Nodes;
}

export interface HtmlSAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["s"]>;
  children?: JSX.Nodes;
}

export interface HtmlSampAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["samp"]>;
  children?: JSX.Nodes;
}

export interface HtmlScriptAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["script"]>;
  children?: JSX.Nodes;
  async?: boolean;
  crossorigin?: "anonymous" | "use-credentials";
  defer?: boolean;
  integrity?: string;
  nomodule?: boolean;
  referrerpolicy?:
    | ""
    | "no-referrer"
    | "no-referrer-when-downgrade"
    | "same-origin"
    | "origin"
    | "strict-origin"
    | "origin-when-cross-origin"
    | "strict-origin-when-cross-origin"
    | "unsafe-url";
  src?: string;
  blocking?: string;
  charset?: string;
  fetchpriority?: string;
  type?: string;
}

export interface HtmlSectionAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["section"]>;
  children?: JSX.Nodes;
}

export interface HtmlSelectAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["select"]>;
  children?: JSX.Nodes;
  autofocus?: boolean;
  disabled?: boolean;
  multiple?: boolean;
  required?: boolean;
  size?: number | string;
  autocomplete?: string;
  form?: string;
  name?: string;
}

export interface HtmlSlotAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["slot"]>;
  children?: JSX.Nodes;
  name?: string;
}

export interface HtmlSmallAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["small"]>;
  children?: JSX.Nodes;
}

export interface HtmlSourceAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["source"]>;
  type?: string;
  media?: string;
  src?: string;
  srcset?: string;
  sizes?: string;
  width?: number | string;
  height?: number | string;
}

export interface HtmlSpanAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["span"]>;
  children?: JSX.Nodes;
}

export interface HtmlStrongAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["strong"]>;
  children?: JSX.Nodes;
}

export interface HtmlStyleAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["style"]>;
  children?: JSX.Nodes;
  blocking?: string;
  media?: string;
  type?: string;
}

export interface HtmlSubAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["sub"]>;
  children?: JSX.Nodes;
}

export interface HtmlSummaryAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["summary"]>;
  children?: JSX.Nodes;
}

export interface HtmlSupAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["sup"]>;
  children?: JSX.Nodes;
}

export interface HtmlSvgAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<SVGElement>;
  children?: JSX.Nodes;
}

export interface HtmlTableAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["table"]>;
  children?: JSX.Nodes;
  border?: string;
}

export interface HtmlTbodyAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["tbody"]>;
  children?: JSX.Nodes;
}

export interface HtmlTdAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["td"]>;
  children?: JSX.Nodes;
  colspan?: number | string;
  rowspan?: number | string;
  abbr?: string;
  headers?: string;
}

export interface HtmlTemplateAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["template"]>;
  children?: JSX.Nodes;
  shadowrootclonable?: string;
  shadowrootdelegatesfocus?: string;
  shadowrootmode?: string;
}

export interface HtmlTextareaAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["textarea"]>;
  children?: JSX.Nodes;
  autocomplete?: string;
  autofocus?: boolean;
  cols?: number | string;
  disabled?: boolean;
  maxlength?: number | string;
  minlength?: number | string;
  readonly?: boolean;
  required?: boolean;
  rows?: number | string;
  wrap?: "hard" | "soft";
  dirname?: string;
  form?: string;
  name?: string;
  placeholder?: string;
}

export interface HtmlTfootAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["tfoot"]>;
  children?: JSX.Nodes;
}

export interface HtmlThAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["th"]>;
  children?: JSX.Nodes;
  colspan?: number | string;
  rowspan?: number | string;
  scope?: "row" | "col" | "rowgroup" | "colgroup";
  abbr?: string;
  headers?: string;
}

export interface HtmlTheadAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["thead"]>;
  children?: JSX.Nodes;
}

export interface HtmlTimeAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["time"]>;
  children?: JSX.Nodes;
  datetime?: string;
}

export interface HtmlTitleAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["title"]>;
  children?: JSX.Nodes;
}

export interface HtmlTrAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["tr"]>;
  children?: JSX.Nodes;
}

export interface HtmlTrackAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["track"]>;
  default?: string;
  kind?: string;
  label?: string;
  src?: string;
  srclang?: string;
}

export interface HtmlUAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["u"]>;
  children?: JSX.Nodes;
}

export interface HtmlUlAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["ul"]>;
  children?: JSX.Nodes;
}

export interface HtmlVarAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["var"]>;
  children?: JSX.Nodes;
}

export interface HtmlVideoAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["video"]>;
  children?: JSX.Nodes;
  crossorigin?: "anonymous" | "use-credentials";
  height?: number | string;
  itemprop?: string;
  preload?: "none" | "metadata" | "auto";
  width?: number | string;
  autoplay?: string;
  controls?: string;
  loop?: string;
  muted?: string;
  playsinline?: string;
  poster?: string;
  src?: string;
}

export interface HtmlWbrAttributes extends GlobalHtmlAttributes {
  ref?: RefCallback<HTMLElementTagNameMap["wbr"]>;
}

export type HtmlAttributesByTag = {
  a: HtmlAAttributes;
  abbr: HtmlAbbrAttributes;
  address: HtmlAddressAttributes;
  area: HtmlAreaAttributes;
  article: HtmlArticleAttributes;
  aside: HtmlAsideAttributes;
  audio: HtmlAudioAttributes;
  b: HtmlBAttributes;
  base: HtmlBaseAttributes;
  bdi: HtmlBdiAttributes;
  bdo: HtmlBdoAttributes;
  blockquote: HtmlBlockquoteAttributes;
  body: HtmlBodyAttributes;
  br: HtmlBrAttributes;
  button: HtmlButtonAttributes;
  canvas: HtmlCanvasAttributes;
  caption: HtmlCaptionAttributes;
  cite: HtmlCiteAttributes;
  code: HtmlCodeAttributes;
  col: HtmlColAttributes;
  colgroup: HtmlColgroupAttributes;
  data: HtmlDataAttributes;
  datalist: HtmlDatalistAttributes;
  dd: HtmlDdAttributes;
  del: HtmlDelAttributes;
  details: HtmlDetailsAttributes;
  dfn: HtmlDfnAttributes;
  dialog: HtmlDialogAttributes;
  div: HtmlDivAttributes;
  dl: HtmlDlAttributes;
  dt: HtmlDtAttributes;
  em: HtmlEmAttributes;
  embed: HtmlEmbedAttributes;
  fieldset: HtmlFieldsetAttributes;
  figcaption: HtmlFigcaptionAttributes;
  figure: HtmlFigureAttributes;
  footer: HtmlFooterAttributes;
  form: HtmlFormAttributes;
  h1: HtmlH1Attributes;
  h2: HtmlH2Attributes;
  h3: HtmlH3Attributes;
  h4: HtmlH4Attributes;
  h5: HtmlH5Attributes;
  h6: HtmlH6Attributes;
  head: HtmlHeadAttributes;
  header: HtmlHeaderAttributes;
  hgroup: HtmlHgroupAttributes;
  hr: HtmlHrAttributes;
  html: HtmlHtmlAttributes;
  i: HtmlIAttributes;
  iframe: HtmlIframeAttributes;
  img: HtmlImgAttributes;
  input: HtmlInputAttributes;
  ins: HtmlInsAttributes;
  kbd: HtmlKbdAttributes;
  label: HtmlLabelAttributes;
  legend: HtmlLegendAttributes;
  li: HtmlLiAttributes;
  link: HtmlLinkAttributes;
  main: HtmlMainAttributes;
  map: HtmlMapAttributes;
  mark: HtmlMarkAttributes;
  math: HtmlMathAttributes;
  menu: HtmlMenuAttributes;
  meta: HtmlMetaAttributes;
  meter: HtmlMeterAttributes;
  nav: HtmlNavAttributes;
  noscript: HtmlNoscriptAttributes;
  object: HtmlObjectAttributes;
  ol: HtmlOlAttributes;
  optgroup: HtmlOptgroupAttributes;
  option: HtmlOptionAttributes;
  output: HtmlOutputAttributes;
  p: HtmlPAttributes;
  param: HtmlParamAttributes;
  picture: HtmlPictureAttributes;
  pre: HtmlPreAttributes;
  progress: HtmlProgressAttributes;
  q: HtmlQAttributes;
  rp: HtmlRpAttributes;
  rt: HtmlRtAttributes;
  ruby: HtmlRubyAttributes;
  s: HtmlSAttributes;
  samp: HtmlSampAttributes;
  script: HtmlScriptAttributes;
  section: HtmlSectionAttributes;
  select: HtmlSelectAttributes;
  slot: HtmlSlotAttributes;
  small: HtmlSmallAttributes;
  source: HtmlSourceAttributes;
  span: HtmlSpanAttributes;
  strong: HtmlStrongAttributes;
  style: HtmlStyleAttributes;
  sub: HtmlSubAttributes;
  summary: HtmlSummaryAttributes;
  sup: HtmlSupAttributes;
  svg: HtmlSvgAttributes;
  table: HtmlTableAttributes;
  tbody: HtmlTbodyAttributes;
  td: HtmlTdAttributes;
  template: HtmlTemplateAttributes;
  textarea: HtmlTextareaAttributes;
  tfoot: HtmlTfootAttributes;
  th: HtmlThAttributes;
  thead: HtmlTheadAttributes;
  time: HtmlTimeAttributes;
  title: HtmlTitleAttributes;
  tr: HtmlTrAttributes;
  track: HtmlTrackAttributes;
  u: HtmlUAttributes;
  ul: HtmlUlAttributes;
  var: HtmlVarAttributes;
  video: HtmlVideoAttributes;
  wbr: HtmlWbrAttributes;
};
